config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"
  resources :tweets, only: [:index] do
    collection do
      get "create"
      get "notification"
      get "topic"
      get "message"
      get "bookmark"
      get "list"
      get "profile"
      get "info"
    end
    member do
      get "like"
    end
  end
  resources :users, only: [:show] do
    member do
      get "follow"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:account, :name])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_icons

    def create
        @tweet = Tweet.new(tweet_params)
        @tweet.save unless params[:tweet][:text].blank?
    end
    
    def set_icons
        @icons = [{link: "/", text: "", class: "fab fa-twitter"},
                  {link: "/", text: "ホーム", class: "fas fa-home"},
                  {link: "/tweets/topic", text: "話題を検索", class: "fas fa-hashtag"},
                  {link: "/tweets/notification", text: "通知", class: "far fa-bell"},
                  {link: "/tweets/message", text: "メッセージ", class: "far fa-envelope"},
                  {link: "/tweets/bookmark", text: "ブックマーク", class: "far fa-bookmark"},
                  {link: "/tweets/list", text: "リスト", class: "far fa-list-alt"},
                  {link: "/users/#{current_user.id}", text: "プロフィール", class: "far fa-user"},
                  {link: "/tweets/info", text: "もっと見る", class: "fas fa-info-circle"}]
    end

    def like
        @tweet = Tweet.find(params[:id])
        @like = Like.find_by(like_params)
        @notification = Notification.find_by(notification_params)
        @like.blank? ? Like.new(like_params).save : @like.delete
        @like.blank? ? Notification.new(notification_params).save : @notification.delete unless @tweet.user_id == current_user.id
    end

    private
    def tweet_params
        params[:tweet].permit(:text).merge(user_id: current_user.id)
    end

    def like_params
        {user_id: current_user.id, tweet_id: params[:id]}
    end

    def notification_params
        {notifying_id: @tweet.user_id, notified_by_id: current_user.id, tweet_id: @tweet.id}
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < TweetsController
    before_action :set_icons

    def show
        @user = User.find(params[:id])
    end

    def follow
        @follow = Follow.find_by(follow_params)
        @notification = Notification.find_by(notification_params)
        @follow.blank? ? Follow.new(follow_params).save : @follow.delete
        @follow.blank? ? Notification.new(notification_params).save : @notification.delete
    end

    private
    def follow_params
        {following_id: current_user.id, followed_by_id: params[:id]}
    end

    def notification_params
        {notifying_id: params[:id], notified_by_id: current_user.id}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.html.erb
<div class="wrapper-left">
    <% @icons.each do |icon|%>
        <% if icon[:text] == "通知" && !Notification.where(notified_by_id: current_user.id, read: false).blank? %>
            <span class="notification"><%= Notification.where(notified_by_id: current_user.id, read: false).count %></span>
        <% end %>
        <a data-turbolinks="false" href="<%= icon[:link] %>" class="wrapper-left-content <%if icon[:link] == "/tweets/#{action_name}" || action_name == "index" && icon[:text] == "ホーム"%>active<%end%>">
            <span class="wrapper-left-content-icon">
                <i class="<%= icon[:class] %>"></i>
            </span>
            <span class="wrapper-left-content-text">
                <%= icon[:text] %>
            </span>
        </a>
    <% end %>
    <% if user_signed_in? %>
        <%= link_to "ログアウト", "/users/sign_out", class: "sign-button", method: "delete" %>
    <% else %>
        <%= link_to "ログイン", "/users/sign_in", class: "sign-button" %>
    <% end %>
</div>

<style>
    .notification{
        left: 10px;
        width: 15px;
        padding: .5px;
        font-size: 10px;
        margin-top: 13px;
        font-weight: bold;
        text-align: center;
        position: absolute;
        border-radius: 100%;
        border: 1px solid black;
        background-color: #00ACEE;
    }
</style>

app/views/layouts/_tweet.html.erb
<div class="wrapper-right-tweets-tweet">
    <div class="wrapper-right-tweets-tweet-left">
        <i class="fas fa-user"></i>
    </div>
    <div class="wrapper-right-tweets-tweet-right">
        <div class="wrapper-right-tweets-tweet-right-top">
            <%= link_to User.find(t.user_id).name, user_path(User.find(t.user_id).id), class: "wrapper-right-tweets-tweet-right-top-userName" %>
            <span class="wrapper-right-tweets-tweet-right-top-userId">@<%= User.find(t.user_id).account %></span>
            <span class="wrapper-right-tweets-tweet-right-top-time">・<%=time_ago_in_words(t.created_at)%></span>
        </div>
        <div class="wrapper-right-tweets-tweet-right-middle">
            <%=t[:text]%>
        </div>
        <div class="wrapper-right-tweets-tweet-right-bottom">
            <i class="far fa-comment"><span class="rep-num">0</span></i>
            <i class="fas fa-retweet"><span class="ret-num">0</span></i>
            <% if Like.find_by(user_id: current_user.id, tweet_id: t.id) %>
                <i class="fas fa-heart" action="<%= like_tweet_path(t.id) %>" style="color: red;"><span class="hea-num"><%= Like.where(tweet_id: t.id).count %></span></i>
            <% else %>
                <i class="far fa-heart" action="<%= like_tweet_path(t.id) %>"><span class="hea-num"><%= Like.where(tweet_id: t.id).count %></span></i>
            <% end %>
            <i class="far fa-share-square"></i>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.9.0/css/all.css'>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/bookmark.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right">
        <div class="wrapper-right-top">
            <span class="wrapper-right-top-text">ホーム</span>
            <i class="wrapper-right-top-icon fas fa-lightbulb"></i>
        </div>
        <div class="wrapper-right-create">
            <div class="wrapper-right-create-left">
                <i class="fas fa-user"></i>
            </div>
            <div class="wrapper-right-create-right">
                <div class="wrapper-right-create-right-top">
                    <textarea placeholder="いまどうしてる？" class="tweet_input"></textarea>
                </div>
                <div class="wrapper-right-create-right-bottom">
                    <div class="wrapper-right-create-right-bottom-left">
                        <% ["image", "gift", "signal", "smile", "calendar-alt"].each do |c| %>
                            <i class="fas fa-<%= c %>"></i>
                        <% end %>
                    </div>
                    <div class="wrapper-right-create-right-bottom-right">
                        <div class="tweet_submit">ツイートする</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="wrapper-right-tweets">
            <% Tweet.all.order(created_at: :desc).each do |t| %>
                <%= render '/layouts/tweet', {t: t} %>
            <% end %>
        </div>
    </div>
</div>

app/views/tweets/info.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/tweets/list.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/tweets/message.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/tweets/notification.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right">
        <div class="wrapper-right-top">
            <span class="wrapper-right-top-text">通知</span>
            <i class="wrapper-right-top-icon fas fa-cog"></i>
        </div>
        <div class="wrapper-right-tweets">
            <% Notification.all.order(created_at: :desc).each do |n| %>
                <% n.update(read: true) %>
                <div class="wrapper-right-tweets-notification">
                    <div class="wrapper-right-tweets-notification-left">
                        <% if n.tweet_id %>
                            <i class="fas fa-heart"></i>
                        <% else %>
                            <i class="fas fa-user"></i>
                        <% end %>
                    </div>
                    <div class="wrapper-right-tweets-notification-right">
                        <div class="wrapper-right-tweets-notification-right-top">
                            <i class="fas fa-user"></i>
                        </div>
                        <div class="wrapper-right-tweets-notification-right-body">
                            <% if n.tweet_id %>
                                <%= link_to User.find(n.notifying_id).name, user_path(n.notifying_id) %>さんがあなたのツイートをいいねしました<br />
                                <span class="likedTweet"><%= Tweet.find(n.tweet_id).text %></span>
                            <% else %>
                                <%= link_to User.find(n.notifying_id).name, user_path(n.notifying_id) %>さんにフォローされました
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

<style>
    .wrapper-right-tweets-notification:hover{
        cursor: pointer;
        background-color: #111;
    }
    .wrapper-right-tweets-notification{
        display: flex;
        padding: 10px 15px;
        border-bottom: 1px solid rgba(255,255,255,.2);
    }
    .wrapper-right-tweets-notification-left{
        width: 50px;
        display: flex;
        margin-right: 10px;
        justify-content: flex-end;
    }
    .wrapper-right-tweets-notification-left i{
        font-size: 25px;
    }
    .wrapper-right-tweets-notification-left .fa-heart{
        color: #DD1C52;
    }
    .wrapper-right-tweets-notification-left .fa-user{
        color: #00ACEE;
    }
    .wrapper-right-tweets-notification-right-top .fa-user{
        padding-left: 1px;
        width: 27px;
        height: 28px;
        line-height: 28px;
        text-align: center;
        border-radius: 25px;
        background-color: rgba(255,255,255,.3);
    }
    .wrapper-right-tweets-notification-right-body{
        font-size: 15px;
        padding-top: 6px;
    }
    .wrapper-right-tweets-notification-right-body a{
        color: #E0E0E0;
        font-weight: bold;
        text-decoration: none;
    }
    .wrapper-right-tweets-notification-right-body a:hover{
        text-decoration: underline;
    }
    .likedTweet{
        color: rgba(255,255,255,.4);
    }
</style>

app/views/tweets/profile.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/tweets/topic.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right"></div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
    <%= render '/layouts/sidebar', {icons: @icons}%>
    <div class="wrapper-right">
        <div class="wrapper-right-top">
            <span class="wrapper-right-top-text"><%= @user.name %></span>
            <i class="wrapper-right-top-icon fas fa-lightbulb"></i>
        </div>
        <div class="wrapper-right-profile">
            <div class="wrapper-right-profile-top">
                <i class="fas fa-user"></i>
                <% if @user.id != current_user.id %>
                    <span class="follow-button" action="<%= follow_user_path(@user) %>">
                        <% if Follow.find_by(following_id: current_user.id, followed_by_id: @user.id) %>
                            フォロー中
                        <% else %>
                            フォロー
                        <% end %>
                    </span>
                <% end %>
            </div>
            <div class="wrapper-right-profile-userName"><%= @user.name %></div>
            <div class="wrapper-right-profile-accountId">@<%= @user.account %></div>
            <div class="wrapper-right-profile-text">哲学とプログラミングを愛する26歳現役エンジニア。初心者向けWEBプログラミング情報サイト『ONSEO』運営。本業副業共にプログラミング一筋。海外向けエンジニア教育ビジネスの構想中。1日22時間作業のショートスリーパー。毎日こつこつビジネスとコンテンツを量産中です</div>
            <div class="wrapper-right-profile-calendar"><i class="far fa-calendar-alt"></i><%= @user.created_at.strftime("%Y年%m月") %>からTwitterを利用しています</div>
            <div class="wrapper-right-profile-follows">
                <span class="follow"><%= Follow.where(following_id: @user.id).count %></span>
                <span class="wrapper-right-profile-follows-ftext">フォロー</span>
                <span class="follower"><%= Follow.where(followed_by_id: @user.id).count %></span>
                <span class="wrapper-right-profile-follows-ftext">フォロワー</span>
            </div>
        </div>
        <div class="wrapper-right-tweets">
            <% Tweet.where(user_id: @user.id).order(created_at: :desc).each do |t| %>
                <%= render '/layouts/tweet', {t: t} %>
            <% end %>
        </div>
    </div>
</div>

<style>
    .wrapper-right-profile-top{
        display: flex;
        align-items: flex-end;
        justify-content: space-between;
    }
    .follow-button{
        width: 120px;
        padding: 7px 0;
        font-size: 15px;
        cursor: pointer;
        font-weight: bold;
        text-align: center;
        border-radius: 39px;
        background-color: #00ACEE;
    }
    .follow-button:hover{
        background-color: #0096D1;
    }
</style>

<script>
    $(()=>{
        let setFollowButton = (s)=>{
            s.text('フォロー中')
            .hover(()=>{
                s.text('フォロー解除').css('background-color', '#CA2154')
            }, ()=>{
                s.text('フォロー中').css('background-color', '')
            })
        }
        let setRemoveButton = (s)=>{
            s.text('フォロー')
            .hover(()=>{
                s.text('フォローする').css('background-color', '#0096D1')
            }, ()=>{
                s.text('フォロー')
            })
        }
        let self = $('.follow-button')
        self.text().indexOf('フォロー中') == -1 ? setRemoveButton(self) : setFollowButton(self)
        $(document).on('click', '.follow-button', function(){
            self = $(this)
            $.get({
                url: self.attr('action')
            }).done((res)=>{
                res.flag ? setFollowButton(self) : setRemoveButton(self)
                $('.follower').text(res.count)
            })
        })
    })
</script>